export const modelData = [
  {
    model_name: "Model_DJkHeu",
    model_type: "Classification",
    description: "A Decision Tree model used for 9iSlzm6xC1nk.",
    created_on: "2024-01-26",
    last_trained_on: "2024-02-16",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_w3N3xp",
    model_type: "Neural Network",
    description: "A Classification model used for alGESMyGCER0.",
    created_on: "2022-03-22",
    last_trained_on: "2024-09-07",
    status: "Pending",
    id: "#5602",
  },
  {
    model_name: "Model_tCnTWm",
    model_type: "Neural Network",
    description: "A Decision Tree model used for y3w2AIH5s9WM.",
    created_on: "2025-01-07",
    last_trained_on: "2025-01-07",
    status: "In Progress",
    id: "#5603",
  },
  {
    model_name: "Model_6sO7KW",
    model_type: "Classification",
    description: "A Neural Network model used for V3eExeuN9yy3.",
    created_on: "2024-02-08",
    last_trained_on: "2024-03-12",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_shDZVX",
    model_type: "Regression",
    description: "A Decision Tree model used for cRorjDSAiloC.",
    created_on: "2021-09-19",
    last_trained_on: "2024-02-20",
    status: "Failed",
    id: "#5605",
  },
  {
    model_name: "Model_rcuy2c",
    model_type: "Decision Tree",
    description: "A Classification model used for dkxkVan6CnhI.",
    created_on: "2020-07-25",
    last_trained_on: "2023-05-24",
    status: "Pending",
    id: "#5606",
  },
  {
    model_name: "Model_YWIdic",
    model_type: "Decision Tree",
    description: "A Neural Network model used for 6lSgHrupJjvj.",
    created_on: "2022-08-16",
    last_trained_on: "2024-12-14",
    status: "Failed",
    id: "#5607",
  },
  {
    model_name: "Model_NlWpHp",
    model_type: "Clustering",
    description: "A Decision Tree model used for z9IL28VdCgeY.",
    created_on: "2024-04-24",
    last_trained_on: "2024-12-20",
    status: "Completed",
    id: "#5608",
  },
  {
    model_name: "Model_4e1HiN",
    model_type: "Decision Tree",
    description: "A Neural Network model used for ZkJbbHN4hN9e.",
    created_on: "2021-10-06",
    last_trained_on: "2022-05-31",
    status: "Pending",
    id: "#5609",
  },
  {
    model_name: "Model_IEIkGH",
    model_type: "Decision Tree",
    description: "A Classification model used for pfZm8NnHhwmJ.",
    created_on: "2023-12-22",
    last_trained_on: "2024-07-19",
    status: "Pending",
    id: "#5610",
  },
  {
    model_name: "Model_6vUNpg",
    model_type: "Clustering",
    description: "A Neural Network model used for fZiT6BCApGxK.",
    created_on: "2022-01-06",
    last_trained_on: "2022-06-21",
    status: "Completed",
    id: "#5611",
  },
  {
    model_name: "Model_P31oj7",
    model_type: "Clustering",
    description: "A Clustering model used for uaEldCoZDpO8.",
    created_on: "2020-09-11",
    last_trained_on: "2023-07-19",
    status: "Completed",
    id: "#5612",
  },
  {
    model_name: "Model_KL7Rzg",
    model_type: "Clustering",
    description: "A Clustering model used for bqhA2wgYEZy9.",
    created_on: "2022-10-26",
    last_trained_on: "2024-01-13",
    status: "In Progress",
    id: "#5613",
  },
  {
    model_name: "Model_zBgOyD",
    model_type: "Neural Network",
    description: "A Decision Tree model used for qraJlw5iCXzD.",
    created_on: "2024-09-15",
    last_trained_on: "2024-11-29",
    status: "Pending",
    id: "#5614",
  },
  {
    model_name: "Model_fGZPl5",
    model_type: "Clustering",
    description: "A Decision Tree model used for O9IAqiEhwj1y.",
    created_on: "2024-11-05",
    last_trained_on: "2024-12-24",
    status: "Completed",
    id: "#5615",
  },
  {
    model_name: "Model_1BIpre",
    model_type: "Neural Network",
    description: "A Classification model used for QcEt7hVu3fMM.",
    created_on: "2020-11-14",
    last_trained_on: "2021-10-16",
    status: "Failed",
    id: "#5616",
  },
  {
    model_name: "Model_0XMGDH",
    model_type: "Neural Network",
    description: "A Clustering model used for ebrLZ0iPCNR7.",
    created_on: "2024-01-19",
    last_trained_on: "2024-04-08",
    status: "Completed",
    id: "#5617",
  },
  {
    model_name: "Model_ttypIT",
    model_type: "Regression",
    description: "A Classification model used for di1mJbU1Athw.",
    created_on: "2020-05-03",
    last_trained_on: "2024-09-27",
    status: "Failed",
    id: "#5618",
  },
  {
    model_name: "Model_if9XJG",
    model_type: "Clustering",
    description: "A Neural Network model used for zb9zrCHJdWXO.",
    created_on: "2022-09-28",
    last_trained_on: "2023-08-11",
    status: "Pending",
    id: "#5619",
  },
  {
    model_name: "Model_jEY5Pa",
    model_type: "Clustering",
    description: "A Clustering model used for tXk4V21ybHLU.",
    created_on: "2022-02-22",
    last_trained_on: "2022-09-21",
    status: "Completed",
    id: "#5620",
  },
  {
    model_name: "Model_oGsc0p",
    model_type: "Neural Network",
    description: "A Clustering model used for MFl8ApDLl1ZT.",
    created_on: "2021-08-15",
    last_trained_on: "2023-07-23",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_a9tbD5",
    model_type: "Decision Tree",
    description: "A Classification model used for 29jV4BG8dZXO.",
    created_on: "2020-11-29",
    last_trained_on: "2023-10-12",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_5PVbiW",
    model_type: "Neural Network",
    description: "A Regression model used for 1YiaSmC6CPP2.",
    created_on: "2023-09-05",
    last_trained_on: "2023-09-18",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_ok4mnH",
    model_type: "Classification",
    description: "A Classification model used for tIX7vH47NHUO.",
    created_on: "2024-11-09",
    last_trained_on: "2024-12-22",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_b9JQwc",
    model_type: "Neural Network",
    description: "A Clustering model used for DiMBMksEfmUc.",
    created_on: "2023-05-08",
    last_trained_on: "2024-03-03",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_tCcODX",
    model_type: "Neural Network",
    description: "A Decision Tree model used for GgulkE59bNQu.",
    created_on: "2020-06-22",
    last_trained_on: "2023-01-03",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_pCNKyU",
    model_type: "Classification",
    description: "A Regression model used for 6MsFdM1GA0Xm.",
    created_on: "2021-05-23",
    last_trained_on: "2024-05-31",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_Gscrvc",
    model_type: "Decision Tree",
    description: "A Clustering model used for N3deIIdLNoJE.",
    created_on: "2022-09-30",
    last_trained_on: "2023-09-08",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_Z5Ddv0",
    model_type: "Regression",
    description: "A Clustering model used for qd9nMQWW7d9U.",
    created_on: "2024-02-07",
    last_trained_on: "2024-02-20",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_KcTafl",
    model_type: "Classification",
    description: "A Regression model used for rdUJtZJwCdxF.",
    created_on: "2023-04-04",
    last_trained_on: "2025-01-02",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_l6WteA",
    model_type: "Decision Tree",
    description: "A Neural Network model used for YJ70ZZI29uxL.",
    created_on: "2022-01-24",
    last_trained_on: "2023-02-19",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_GX74Ne",
    model_type: "Decision Tree",
    description: "A Classification model used for bivwAzTOfgwQ.",
    created_on: "2022-02-23",
    last_trained_on: "2024-01-18",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_CsjZDn",
    model_type: "Decision Tree",
    description: "A Regression model used for vQJVNRjT8bLe.",
    created_on: "2024-01-26",
    last_trained_on: "2024-06-04",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_7OXiUn",
    model_type: "Clustering",
    description: "A Classification model used for hqW1qWrafnWW.",
    created_on: "2020-02-10",
    last_trained_on: "2023-06-04",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_SuhEZD",
    model_type: "Classification",
    description: "A Regression model used for ToC0RFJ2vqnA.",
    created_on: "2024-09-09",
    last_trained_on: "2024-12-31",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_zDjpzL",
    model_type: "Neural Network",
    description: "A Clustering model used for XT4awcleNDER.",
    created_on: "2021-12-09",
    last_trained_on: "2024-09-19",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_OOICsd",
    model_type: "Classification",
    description: "A Neural Network model used for m2IPRP5M2ZYm.",
    created_on: "2021-02-14",
    last_trained_on: "2022-04-09",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_LYV9z0",
    model_type: "Neural Network",
    description: "A Classification model used for WFYHfSZnvfc3.",
    created_on: "2024-10-29",
    last_trained_on: "2024-11-30",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_LPAroA",
    model_type: "Clustering",
    description: "A Regression model used for Poi0VeDvG4uR.",
    created_on: "2022-02-06",
    last_trained_on: "2023-12-03",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_40VMRw",
    model_type: "Classification",
    description: "A Decision Tree model used for rWqUvKa5MVSO.",
    created_on: "2021-08-14",
    last_trained_on: "2023-09-04",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_ELAnb3",
    model_type: "Classification",
    description: "A Regression model used for XNRjhF0HluQj.",
    created_on: "2022-01-18",
    last_trained_on: "2024-11-18",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_HdsghJ",
    model_type: "Clustering",
    description: "A Neural Network model used for XKNPGJHDYcdV.",
    created_on: "2022-09-10",
    last_trained_on: "2024-12-07",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_qTWvc7",
    model_type: "Classification",
    description: "A Regression model used for 93nFFUQoDvys.",
    created_on: "2024-09-14",
    last_trained_on: "2024-12-24",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_fBjpHZ",
    model_type: "Decision Tree",
    description: "A Classification model used for gARZXUTPXZtk.",
    created_on: "2020-06-08",
    last_trained_on: "2021-03-04",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_R7gfzg",
    model_type: "Classification",
    description: "A Clustering model used for wbOSSROawTWB.",
    created_on: "2024-09-23",
    last_trained_on: "2024-10-27",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_Dcd2a0",
    model_type: "Classification",
    description: "A Decision Tree model used for 37tm7hxMKGXf.",
    created_on: "2024-05-02",
    last_trained_on: "2024-10-29",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_GJCLgd",
    model_type: "Regression",
    description: "A Regression model used for pNLMJlDr1WcW.",
    created_on: "2020-03-18",
    last_trained_on: "2023-12-01",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_kL5An7",
    model_type: "Classification",
    description: "A Regression model used for 33buTjwAI8tq.",
    created_on: "2020-04-08",
    last_trained_on: "2024-02-16",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_niqWzV",
    model_type: "Classification",
    description: "A Regression model used for SGX20OQxaALc.",
    created_on: "2023-09-12",
    last_trained_on: "2024-10-12",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_KmZuU1",
    model_type: "Clustering",
    description: "A Neural Network model used for qKcDVK9ulUhH.",
    created_on: "2020-08-29",
    last_trained_on: "2021-10-27",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_xl9uL2",
    model_type: "Neural Network",
    description: "A Decision Tree model used for nRAm1OB5lHvi.",
    created_on: "2020-08-22",
    last_trained_on: "2022-10-01",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_jhKvqG",
    model_type: "Classification",
    description: "A Clustering model used for tzLweYWWmeo2.",
    created_on: "2021-12-30",
    last_trained_on: "2024-03-13",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_D8aBhx",
    model_type: "Neural Network",
    description: "A Neural Network model used for 0UrmiJlJ05jK.",
    created_on: "2021-06-12",
    last_trained_on: "2022-08-28",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_98tnWI",
    model_type: "Neural Network",
    description: "A Decision Tree model used for yUlFvQ6bsQ45.",
    created_on: "2023-09-25",
    last_trained_on: "2024-04-25",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_1RVaJn",
    model_type: "Classification",
    description: "A Regression model used for bhkinQ9823SH.",
    created_on: "2024-05-11",
    last_trained_on: "2024-07-01",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_RarjWn",
    model_type: "Classification",
    description: "A Regression model used for GMvfLKE5ymIr.",
    created_on: "2020-06-22",
    last_trained_on: "2022-01-06",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_990pBg",
    model_type: "Regression",
    description: "A Neural Network model used for ywXRFcF6omj4.",
    created_on: "2023-07-07",
    last_trained_on: "2024-11-16",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_XpjpmV",
    model_type: "Decision Tree",
    description: "A Classification model used for Pdv3yDyUbTzi.",
    created_on: "2022-06-29",
    last_trained_on: "2024-04-06",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_Gu6Vjq",
    model_type: "Decision Tree",
    description: "A Decision Tree model used for AVxTibaXtKjG.",
    created_on: "2022-01-16",
    last_trained_on: "2024-04-13",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_efHqO0",
    model_type: "Neural Network",
    description: "A Regression model used for TgtHYb4GGAdj.",
    created_on: "2023-11-24",
    last_trained_on: "2024-01-14",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_MVWVaR",
    model_type: "Clustering",
    description: "A Classification model used for OUCGnxkmLd8w.",
    created_on: "2020-07-20",
    last_trained_on: "2020-11-19",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_y5jRs3",
    model_type: "Regression",
    description: "A Clustering model used for nYyJJC0MjrUM.",
    created_on: "2022-10-18",
    last_trained_on: "2024-09-06",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_xRMs9Y",
    model_type: "Neural Network",
    description: "A Classification model used for BQh6Bled8ObY.",
    created_on: "2020-07-06",
    last_trained_on: "2020-07-14",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_5mDMfy",
    model_type: "Regression",
    description: "A Neural Network model used for VYsUXQW4F5n2.",
    created_on: "2022-07-07",
    last_trained_on: "2024-11-15",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_I5A1hW",
    model_type: "Decision Tree",
    description: "A Classification model used for gE5Wvb86hklO.",
    created_on: "2022-12-26",
    last_trained_on: "2024-09-30",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_hDk7sn",
    model_type: "Classification",
    description: "A Regression model used for mk3wv8aHWRxZ.",
    created_on: "2024-09-16",
    last_trained_on: "2024-10-18",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_nC94td",
    model_type: "Neural Network",
    description: "A Regression model used for wmGtb8spkQ86.",
    created_on: "2020-12-18",
    last_trained_on: "2021-04-01",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_Q0j5eu",
    model_type: "Classification",
    description: "A Classification model used for rIaOqUYog37H.",
    created_on: "2020-11-12",
    last_trained_on: "2021-11-01",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_gaTKVF",
    model_type: "Classification",
    description: "A Neural Network model used for mmYdG6xSSzvC.",
    created_on: "2022-05-22",
    last_trained_on: "2022-12-11",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_mIdApY",
    model_type: "Classification",
    description: "A Decision Tree model used for a1qeLIN3L5S2.",
    created_on: "2024-07-24",
    last_trained_on: "2024-12-17",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_rddWPY",
    model_type: "Regression",
    description: "A Classification model used for Uu0A0ljMUbYA.",
    created_on: "2023-08-02",
    last_trained_on: "2024-02-27",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_RwbIJQ",
    model_type: "Classification",
    description: "A Classification model used for fPp0j5n9KKDo.",
    created_on: "2021-09-03",
    last_trained_on: "2023-01-22",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_GtxPVl",
    model_type: "Classification",
    description: "A Neural Network model used for zs360py8zkFI.",
    created_on: "2021-01-04",
    last_trained_on: "2024-02-01",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_2oc3LX",
    model_type: "Decision Tree",
    description: "A Decision Tree model used for t1KCcC2TWdqc.",
    created_on: "2022-11-01",
    last_trained_on: "2024-04-25",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_ceFl5Y",
    model_type: "Clustering",
    description: "A Classification model used for 4IUEtvvTbXhd.",
    created_on: "2022-10-18",
    last_trained_on: "2023-02-14",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_H7Ahuq",
    model_type: "Classification",
    description: "A Clustering model used for GDdCHHKsNcbf.",
    created_on: "2020-04-06",
    last_trained_on: "2023-04-12",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_OUaSUl",
    model_type: "Regression",
    description: "A Regression model used for o6MKZQEWzXYC.",
    created_on: "2020-03-11",
    last_trained_on: "2020-07-10",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_e2Cc0S",
    model_type: "Clustering",
    description: "A Classification model used for jByXplDVvVVL.",
    created_on: "2023-09-24",
    last_trained_on: "2024-12-15",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_sgyZlF",
    model_type: "Neural Network",
    description: "A Regression model used for ddqL8V6uiNuH.",
    created_on: "2022-12-01",
    last_trained_on: "2024-05-29",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_SdqrGy",
    model_type: "Regression",
    description: "A Classification model used for 9689HzZC8oRe.",
    created_on: "2024-10-09",
    last_trained_on: "2024-12-07",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_0gsh0E",
    model_type: "Decision Tree",
    description: "A Classification model used for 2lXoYxIl0LeO.",
    created_on: "2021-02-26",
    last_trained_on: "2024-01-03",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_ofUq8F",
    model_type: "Decision Tree",
    description: "A Neural Network model used for a0wotmtNfn90.",
    created_on: "2022-09-14",
    last_trained_on: "2024-11-20",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_9RJqbT",
    model_type: "Decision Tree",
    description: "A Decision Tree model used for wyOXcblHEP4f.",
    created_on: "2024-10-16",
    last_trained_on: "2025-01-07",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_mCB7uq",
    model_type: "Clustering",
    description: "A Regression model used for PQAU4VAEuNtI.",
    created_on: "2020-07-20",
    last_trained_on: "2022-02-19",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_gPv3aX",
    model_type: "Decision Tree",
    description: "A Regression model used for ghI1aEFDU2TL.",
    created_on: "2020-05-15",
    last_trained_on: "2024-11-07",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_Flj4yy",
    model_type: "Clustering",
    description: "A Decision Tree model used for BkCcSR6GqEg3.",
    created_on: "2021-12-09",
    last_trained_on: "2022-07-12",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_eRHWvT",
    model_type: "Neural Network",
    description: "A Clustering model used for 7PAMGVXO8yEO.",
    created_on: "2022-07-26",
    last_trained_on: "2024-03-09",
    status: "In Progress",
    id: "#5604",
  },
  {
    model_name: "Model_wq7FBw",
    model_type: "Classification",
    description: "A Neural Network model used for Ef4nNGuyk133.",
    created_on: "2021-10-13",
    last_trained_on: "2023-01-14",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_DQYlKz",
    model_type: "Clustering",
    description: "A Clustering model used for XFlgIhhZiHyT.",
    created_on: "2020-04-04",
    last_trained_on: "2022-07-26",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_z6fWx8",
    model_type: "Neural Network",
    description: "A Clustering model used for LpQfvB66nd4v.",
    created_on: "2022-09-29",
    last_trained_on: "2023-09-14",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_mOiJYb",
    model_type: "Classification",
    description: "A Decision Tree model used for Oxnxsqy6qJT8.",
    created_on: "2024-04-19",
    last_trained_on: "2024-04-28",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_LKcTXC",
    model_type: "Classification",
    description: "A Neural Network model used for ZkWFUX9AX306.",
    created_on: "2023-02-25",
    last_trained_on: "2024-09-13",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_aYaBAo",
    model_type: "Neural Network",
    description: "A Decision Tree model used for PMFoQrSFtObH.",
    created_on: "2023-05-04",
    last_trained_on: "2023-07-18",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_jnNMQ0",
    model_type: "Neural Network",
    description: "A Classification model used for 0VXJg6SEB5I8.",
    created_on: "2023-04-21",
    last_trained_on: "2023-11-15",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_2cffts",
    model_type: "Regression",
    description: "A Decision Tree model used for nfTttI8eSWp5.",
    created_on: "2021-12-27",
    last_trained_on: "2022-12-21",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_0Towc9",
    model_type: "Decision Tree",
    description: "A Decision Tree model used for 8RUUo5yeI3p4.",
    created_on: "2023-12-17",
    last_trained_on: "2024-05-10",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_pEUA6j",
    model_type: "Decision Tree",
    description: "A Clustering model used for A2xZKcNbSb93.",
    created_on: "2023-02-12",
    last_trained_on: "2024-07-14",
    status: "Completed",
    id: "#5602",
  },
  {
    model_name: "Model_GCBr7S",
    model_type: "Neural Network",
    description: "A Clustering model used for WTnJH8Tyv2K9.",
    created_on: "2020-08-23",
    last_trained_on: "2021-06-10",
    status: "Failed",
    id: "#5602",
  },
  {
    model_name: "Model_mEqwLv",
    model_type: "Neural Network",
    description: "A Neural Network model used for MTqupo5ji9TJ.",
    created_on: "2021-07-15",
    last_trained_on: "2022-12-05",
    status: "Pending",
    id: "#5601",
  },
  {
    model_name: "Model_rLrI3M",
    model_type: "Neural Network",
    description: "A Regression model used for 5OPRusGurzoL.",
    created_on: "2022-02-15",
    last_trained_on: "2022-11-14",
    status: "Failed",
    id: "#5602",
  },
];

export default modelData;
